services:
  - type: web
    name: gc_music_api_g1
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gc_music_api_g1.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gc_music_db
          property: postgres://postgres:[YOUR-PASSWORD]@db.vlrpmbtshktmdvhjkjox.supabase.co:6543/postgres
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4