services:
  - type: web
    name: gc_music_api_g1
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gc_music_api_g1.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres://postgres:Wm7xWAqheVU6StoZ@db.vlrpmbtshktmdvhjkjox.supabase.co:6543/postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4